import type { Metadata, Viewport } from "next";
import "./globals.css";
import { CartProvider } from "@/lib/cart";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import MetaPixel from "@/components/MetaPixel";
import { site } from "@/data/site";
import { restaurantSchema } from "@/lib/seo";

const ogTitle = `${site.name} · Phở kuhinja u ${site.cityLoc}`;

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: ogTitle,
    template: `%s · ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "phở",
    "pho",
    "phở Novi Sad",
    "pho dostava Novi Sad",
    "vijetnamska kuhinja",
    "vijetnamska hrana Novi Sad",
    "vijetnamski restoran Novi Sad",
    "phở restoran Novi Sad",
    "restoran Stražilovska",
    "dostava hrane Novi Sad",
    "goveđa supa dostava",
    "pirinčani rezanci",
    "azijska hrana Novi Sad",
  ],
  authors: [{ name: site.name }],
  creator: site.name,
  publisher: site.name,
  // NB: canonical is set per-page (a layout-level canonical would cascade "/" onto
  // every route). See each page's metadata export.
  manifest: "/manifest.webmanifest",
  icons: {
    icon: [
      { url: "/icon.svg", type: "image/svg+xml" },
      { url: "/icon-192.png", type: "image/png", sizes: "192x192" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
  openGraph: {
    type: "website",
    locale: "sr_RS",
    siteName: site.name,
    title: ogTitle,
    description: site.description,
    url: site.url,
    // og:image (+ dimensions) is injected automatically from app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: ogTitle,
    description: site.description,
    // twitter:image falls back to og:image generated by app/opengraph-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  category: "food",
};

export const viewport: Viewport = {
  themeColor: "#0A0A0A",
  colorScheme: "dark",
};

/**
 * The direction contract. Emitted as a real HTML comment so it survives the
 * production build and can be audited against the rendered page.
 */
const CONTRACT = `
THESIS: A kitchen that cooks one dish should look like it has nothing to hide, so the
page states contents and prices at full contrast and shows no picture of the food.
There is no photography and none is coming; type and flat colour carry the product.
OWN-WORLD: True black ground, white type and rules, three saturated inks used at full
strength: chili red, jade green, gold yellow. Colour fields carry black type, never
white. No gradients, no glow, no tints, no illustration. Archivo expanded caps for
display, Chivo for text, Chivo Mono for prices. Heavy 3px rules.
STORY: The visitor learns the broth is cooked six hours from bones, sees that the menu
is two lines long, and either walks to Stražilovska 10 or orders.
FIRST VIEWPORT: Asymmetric. Headline and deck left (7 cols), the contents panel boxed
on the right (5 cols). Primary action sits under the deck.
MOTION: None on hover. Interactive elements swap colour instantly, with no transition,
transform or shadow. The only animation left is the payment spinner.
FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md
`;

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="sr">
      <head>
        {/* Fonts are self-hosted (globals.css @font-face). Preload the two latin
            files, the critical path for first paint; the vietnamese/latin-ext
            subsets stream in via unicode-range as their glyphs appear. */}
        <link
          rel="preload"
          href="/fonts/archivo-latin.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/chivo-latin.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <div hidden dangerouslySetInnerHTML={{ __html: `<!--${CONTRACT}-->` }} />
        <JsonLd data={restaurantSchema()} />
        <MetaPixel />
        <CartProvider>
          <Nav />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
