import type { Metadata, Viewport } from "next";
import "./globals.css";
import { CartProvider } from "@/lib/cart";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import MetaPixel from "@/components/MetaPixel";
import { site } from "@/data/site";
import { restaurantSchema } from "@/lib/seo";

const ogTitle = `${site.name} — Phở kuhinja i dostava · ${site.city}`;

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: ogTitle,
    template: `%s · ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "phở",
    "pho",
    "phở Novi Sad",
    "pho dostava Novi Sad",
    "vijetnamska kuhinja",
    "vijetnamska hrana Novi Sad",
    "vijetnamski restoran Novi Sad",
    "dostava hrane Novi Sad",
    "goveđa supa dostava",
    "pirinčani rezanci",
    "azijska hrana Novi Sad",
  ],
  authors: [{ name: site.name }],
  creator: site.name,
  publisher: site.name,
  // NB: canonical is set per-page (a layout-level canonical would cascade "/" onto
  // every route). See each page's metadata export.
  manifest: "/manifest.webmanifest",
  icons: { icon: [{ url: "/icon.svg", type: "image/svg+xml" }] },
  openGraph: {
    type: "website",
    locale: "sr_RS",
    siteName: site.name,
    title: ogTitle,
    description: site.description,
    url: site.url,
    // og:image (+ dimensions) is injected automatically from app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: ogTitle,
    description: site.description,
    // twitter:image falls back to og:image generated by app/opengraph-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  category: "food",
};

export const viewport: Viewport = {
  themeColor: "#141619",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="sr">
      <head>
        {/* Fonts are self-hosted (globals.css @font-face). Preload the two latin
            files — the critical path for first paint; the vietnamese/latin-ext
            subsets stream in via unicode-range as their glyphs appear. */}
        <link
          rel="preload"
          href="/fonts/bricolage-latin.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/inter-latin.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
      </head>
      <body>
        <JsonLd data={restaurantSchema()} />
        <MetaPixel />
        <CartProvider>
          <Nav />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
