import type { Metadata, Viewport } from "next";
import "./globals.css";
import { CartProvider } from "@/lib/cart";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import JsonLd from "@/components/JsonLd";
import { site } from "@/data/site";
import { restaurantSchema } from "@/lib/seo";

const ogTitle = `${site.name} — Phở kuhinja i dostava · ${site.city}`;

export const metadata: Metadata = {
  metadataBase: new URL(site.url),
  title: {
    default: ogTitle,
    template: `%s · ${site.name}`,
  },
  description: site.description,
  applicationName: site.name,
  keywords: [
    "phở",
    "pho",
    "phở Novi Sad",
    "pho dostava Novi Sad",
    "vijetnamska kuhinja",
    "vijetnamska hrana Novi Sad",
    "vijetnamski restoran Novi Sad",
    "dostava hrane Novi Sad",
    "goveđa supa dostava",
    "pirinčani rezanci",
    "azijska hrana Novi Sad",
  ],
  authors: [{ name: site.name }],
  creator: site.name,
  publisher: site.name,
  // NB: canonical is set per-page (a layout-level canonical would cascade "/" onto
  // every route). See each page's metadata export.
  manifest: "/manifest.webmanifest",
  icons: { icon: [{ url: "/icon.svg", type: "image/svg+xml" }] },
  openGraph: {
    type: "website",
    locale: "sr_RS",
    siteName: site.name,
    title: ogTitle,
    description: site.description,
    url: site.url,
    // og:image (+ dimensions) is injected automatically from app/opengraph-image.tsx.
  },
  twitter: {
    card: "summary_large_image",
    title: ogTitle,
    description: site.description,
    // twitter:image falls back to og:image generated by app/opengraph-image.tsx.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  category: "food",
};

export const viewport: Viewport = {
  themeColor: "#0C110B",
  colorScheme: "dark",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="sr">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400;12..96,600;12..96,800&family=Inter:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <JsonLd data={restaurantSchema()} />
        <CartProvider>
          <Nav />
          <main>{children}</main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
